import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const currentYear = new Date().getFullYear()
  return (
    <div className={styles.container}>
      <Head>
        <title>Hover and Check</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1> Here is the main </h1>
      </main>

      <footer className={styles.footer}>
        <div> Atsargiai, piktas šuo &copy; { currentYear} </div>
      </footer>
    </div>
  )
}

export default Home
